### ISSUE TITLE
Программная вставка улицы вызывает ошибку parentType must equal "city" 

### ISSUE THREAD

**Issue by lukyoung** [garakh/kladrapi-jsclient#16]
Использую ваш плагин для jQuery. Программно вставляю данные в форму, использую конструкцию:

        $region.kladr({type: $.kladr.type.region, verify: true});
        $district.kladr({type: $.kladr.type.district, verify: true});
        $city.kladr({type: $.kladr.type.city, verify: true});
        $street.kladr({type: $.kladr.type.street, verify: true, withParents: true});
        $building.kladr({type: $.kladr.type.building, verify: true});

        $region.val(options.data.region).trigger('change');
        $district.val(options.data.district).trigger('change');
        $city.val(options.data.city).trigger('change');
        $street.val(options.data.street).trigger('change');
        $building.kladr({'verify': true});
        $building.val(options.data.building).trigger('change');

на $street вылетает с: parentType must equal "city"

**Comment by beliysnow** [comment]
Как указать плагину что именно я от него хочу получить?
Например: г. Москва, г. Москва, ул. Трудовая, 2/21стр1
При восстановлении данных в форму плагин возвращает информацию не об улице Трудовой, а об Аллее Трудовой, т.к. в результатах поиска Аллея Трудовая стоит на первом месте, а Улица Трудовая на втором и на Аллее трудовой нет дома 2/21стр1.
Стандартный запрос к API выглядит так: contentType=street&query=Трудовая&cityId=7700000000000&limit=5
Как указать в запросе какую именно улицу я хочу? Я даже готов хранить у себя идентификаторы улиц, если это как-то поможет...

**Comment by garakh** [comment]
Вы можете указать streetId совместно с contentType = street и пустым query. В этом случае будет поиск по ID улицы, что даст однозначный результат

**Comment by beliysnow** [comment]
Где это указывать?

**Comment by garakh** [comment]
contentType=street&query=&streetId=7700000000000&limit=1

**Comment by beliysnow** [comment]
В плагине этот параметр где-то документирован? Как в плагине его указать? Я не напрямую к API стучусь ведь, а через плагин.

**Comment by garakh** [comment]
В плагине это не указать, т.к. плагин решает немного другие задачи.

**Comment by garakh** [comment]
Попробуйте указать 
parentType - тип родительского объекта, по умолчанию null. — $.kladr.type.street
parentId - идентификатор родительского объекта, по умолчанию null. — ID улицы
type — $.kladr.type.street

**Comment by garakh** [comment]
но в этом случае плагин будет всегда возвращать эту улицу

**Comment by beliysnow** [comment]
Все перепробовал, все равно не получается. Лучше наверное код показать. Примерно такое содержание:
```javascript
	region.kladr({
		type: jQuery.kladr.type.region,
		verify: true,
		check: function( obj ) {
			try {
				if ( obj ) {
					city.kladr( 'parentType', jQuery.kladr.type.region );
					city.kladr( 'parentId', obj.id );
					city.trigger('change');
				}
			} catch ( e ) {}
		}
	});
	city.kladr({
		type: jQuery.kladr.type.city,
		withParents: true,
		verify: true,
		check: function( obj ) {
			try {
				if ( obj ) {
					street.kladr('parentType', jQuery.kladr.type.city);
					street.kladr('parentId', obj.id);
					street.trigger('change');
				}
			} catch ( e ) {}
		}
	});
	street.kladr({
		type: jQuery.kladr.type.street,
		verify: true,
		check: function( obj ) {
			try {
				if ( obj ) {
					building.kladr( 'parentType', jQuery.kladr.type.street );
					building.kladr( 'parentId', obj.id );
					building.trigger('change');
				}
			} catch ( e ) {}
		}
	});

	try {
		region.trigger('change');
	} catch( e ) {}
```

Нужно, чтобы для здания в родители проставилась улица с конкретным streetId – 77000000000293700

**Comment by garakh** [comment]
Я не совсем понимаю вашу задачу. Если нужно проставить конкретный streetId для здания, то установите  building.kladr( 'parentId', '77000000000293700' ); Ваш пример выглядит верным. Пользователь выбирает улицу, ID этой улицы устанавливается родителем для дома.

**Comment by beliysnow** [comment]
Задача такая. 
На 1 этапе пользователь вводит новый адрес, для примера г. Москва, ул. Трудовая, д. 2/21стр1. Эти значения пишутся в базу.
Если пользователь хочет отредактировать эти значения – мне нужно передать их в форму. Для этого я заполняю значения полей формы и дергаю триггер "change" сначала для region, в нем (если найден регион) дергаю триггер "change" для города и т.д.
Все работает нормально, если в городе одна улица Трудовая. В Москве есть улица Трудовая и аллея Трудовая. В плагине я не могу указать что именно мне нужно: улица или аллея, поэтому результат запроса к API – первый результат поиска (contentType=street&query=Трудовая&cityId=7700000000000&limit=5) и это Аллея Трудовая, а не Улица Трудовая. Дальше для здания родителем становится Аллея Трудовая, но на ней нет дома 2/21стр1, поэтому все херится, хотя все данные на 1 шаге были введены корректно.

Задача сводится к тому, чтобы получить от плагина именно ту улицу, которая мне нужна, а не ту, которая будет первой в поиске, т.е. как указать streetId в запросе к API.

**Comment by garakh** [comment]
Понял. Вам надо сохранять не только название улицы, но и ее ID. Например, в той же Москве есть улицы с одинаковым названием (именно улицы, так что там по названию их вообще не отличить)

**Comment by beliysnow** [comment]
Сохраняю. Дальше как и куда это значение подставлять?

**Comment by beliysnow** [comment]
Как указать streetId в запросе к API?

**Comment by garakh** [comment]
Вы имеете в виду js плагин или непосредственно API сервиса ?

**Comment by beliysnow** [comment]
В js плагине. У меня есть streetId. Как сказать плагину, чтобы при инициализации поля ввода он навесил на него улицу с этим streetId?

**Comment by beliysnow** [comment]
Разработчики, ау!
Как указать js плагину, что я хочу получить конкретную улицу? streetId я сохраняю, как передать это в плагин?
3 месяца прошло - решения нет

**Comment by garakh** [comment]
$('input').kladr({
    parentType : $.kladr.type.street,
    parentId  : ,,,
});

**Comment by garex** [comment]
@beliysnow ау, форкни и пофикси. Или закажи платную поддержку, раз сам не в курсе.

**Comment by garakh** [comment]
@beliysnow перечитал спустя столько времени вопрос и понял, что я возможно не совсем верно на него ответил. У плагина есть метод setValueById, который установит в поле значение по ID кладра. Т.е. у вас будет что-то типа 
`
var street = $(...).kladr(...)
street.setValueById(код улицы)
`

смотрите документацию плагина https://github.com/garakh/kladrapi-jsclient
