### ISSUE TITLE
Не находит некоторые дома и улицы в режиме oneString

### ISSUE THREAD

**Issue by kinolaev** [garakh/kladrapi-jsclient#20]
Здравствуйте.
Во-первых, спасибо за ваш труд, отличный проект.

Проблема: в режиме oneString плагин не возращает дом по query "москва клары цеткин 20" и улицу по query "нахабино красноармейская".

Без oneString оба объекта возвращаются.

Проверить можете на вашем сайте в разделе с примерами.

Версия плагина 2.1.3

**Comment by AndrewBerezin** [comment]
Насколько я понимаю, проблнма так и не решена. Я не смог попробовать ввод одной строкой. На http://kladr-api.ru/examples ну никак не получается ввести адрес с подсказками, если выставлен "родитель" Москва или Санкт-Петербург. При вводе букв "мо" получаю список республик.
Запрос к серверу:
http://kladr-api.ru/api.php?callback=jQuery18306845667350028031_1429452791995&cityId=7800000000000&parentType=city&parentId=7800000000000&oneString=true&withParent=true&limit=10&query=%D0%BC%D0%BE&_=1429452824278
Ответ от сервера:
jQuery18306845667350028031_1429452791995({"searchContext":{"oneString":"true","cityId":"7800000000000"
,"query":"\u043c\u043e","withParent":"true","limit":10,"callback":"jQuery18306845667350028031_1429452791995"
},"result":[{"id":"0100000000000","name":"\u0410\u0434\u044b\u0433\u0435\u044f","zip":"385000","type"
:"\u0420\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430","typeShort":"\u0420\u0435\u0441\u043f"
,"okato":"79000000000","contentType":"region","fullName":"\u0420\u0435\u0441\u043f\u0443\u0431\u043b
\u0438\u043a\u0430 \u0410\u0434\u044b\u0433\u0435\u044f"},{"id":"0200000000000","name":"\u0411\u0430
\u0448\u043a\u043e\u0440\u0442\u043e\u0441\u0442\u0430\u043d","zip":"450000","type":"\u0420\u0435\u0441
\u043f\u0443\u0431\u043b\u0438\u043a\u0430","typeShort":"\u0420\u0435\u0441\u043f","okato":"80000000000"
,"contentType":"region","fullName":"\u0420\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430 \u0411
\u0430\u0448\u043a\u043e\u0440\u0442\u043e\u0441\u0442\u0430\u043d"},{"id":"0300000000000","name":"\u0411
\u0443\u0440\u044f\u0442\u0438\u044f","zip":"670000","type":"\u0420\u0435\u0441\u043f\u0443\u0431\u043b
\u0438\u043a\u0430","typeShort":"\u0420\u0435\u0441\u043f","okato":"81000000000","contentType":"region"
,"fullName":"\u0420\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430 \u0411\u0443\u0440\u044f\u0442
\u0438\u044f"},{"id":"0400000000000","name":"\u0410\u043b\u0442\u0430\u0439","zip":"649000","type":"
\u0420\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430","typeShort":"\u0420\u0435\u0441\u043f"
,"okato":"84000000000","contentType":"region","fullName":"\u0420\u0435\u0441\u043f\u0443\u0431\u043b
\u0438\u043a\u0430 \u0410\u043b\u0442\u0430\u0439"},{"id":"0500000000000","name":"\u0414\u0430\u0433
\u0435\u0441\u0442\u0430\u043d","zip":"368000","type":"\u0420\u0435\u0441\u043f\u0443\u0431\u043b\u0438
\u043a\u0430","typeShort":"\u0420\u0435\u0441\u043f","okato":"82000000000","contentType":"region","fullName"
:"\u0420\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430 \u0414\u0430\u0433\u0435\u0441\u0442\u0430
\u043d"},{"id":"0600000000000","name":"\u0418\u043d\u0433\u0443\u0448\u0435\u0442\u0438\u044f","zip"
:"386000","type":"\u0420\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430","typeShort":"\u0420\u0435
\u0441\u043f","okato":"26000000000","contentType":"region","fullName":"\u0420\u0435\u0441\u043f\u0443
\u0431\u043b\u0438\u043a\u0430 \u0418\u043d\u0433\u0443\u0448\u0435\u0442\u0438\u044f"},{"id":"0700000000000"
,"name":"\u041a\u0430\u0431\u0430\u0440\u0434\u0438\u043d\u043e-\u0411\u0430\u043b\u043a\u0430\u0440
\u0441\u043a\u0430\u044f","zip":null,"type":"\u0420\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430"
,"typeShort":"\u0420\u0435\u0441\u043f","okato":"83000000000","contentType":"region","fullName":"\u0420
\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430 \u041a\u0430\u0431\u0430\u0440\u0434\u0438\u043d
\u043e-\u0411\u0430\u043b\u043a\u0430\u0440\u0441\u043a\u0430\u044f"},{"id":"0800000000000","name":"
\u041a\u0430\u043b\u043c\u044b\u043a\u0438\u044f","zip":null,"type":"\u0420\u0435\u0441\u043f\u0443\u0431
\u043b\u0438\u043a\u0430","typeShort":"\u0420\u0435\u0441\u043f","okato":"85000000000","contentType"
:"region","fullName":"\u0420\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430 \u041a\u0430\u043b
\u043c\u044b\u043a\u0438\u044f"},{"id":"0900000000000","name":"\u041a\u0430\u0440\u0430\u0447\u0430\u0435
\u0432\u043e-\u0427\u0435\u0440\u043a\u0435\u0441\u0441\u043a\u0430\u044f","zip":null,"type":"\u0420
\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430","typeShort":"\u0420\u0435\u0441\u043f","okato"
:"91000000000","contentType":"region","fullName":"\u0420\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a
\u0430 \u041a\u0430\u0440\u0430\u0447\u0430\u0435\u0432\u043e-\u0427\u0435\u0440\u043a\u0435\u0441\u0441
\u043a\u0430\u044f"},{"id":"1000000000000","name":"\u041a\u0430\u0440\u0435\u043b\u0438\u044f","zip"
:null,"type":"\u0420\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430","typeShort":"\u0420\u0435
\u0441\u043f","okato":"86000000000","contentType":"region","fullName":"\u0420\u0435\u0441\u043f\u0443
\u0431\u043b\u0438\u043a\u0430 \u041a\u0430\u0440\u0435\u043b\u0438\u044f"}]});

Т.е. возвращается все id верхнего уровня подряд, начиная с 0100000000000 и заканчивая 1000000000000

**Comment by garakh** [comment]
Проблема решена
