### ISSUE TITLE
невозможно вбить адреса

### ISSUE THREAD

**Issue by gvitaly** [garakh/kladrapi-jsclient#27]
Доброе время суток.

За счёт того, что объеденены 3 и 4 уровни кладр
ГГГ – код города;
ППП – код населенного пункта;
не возможно корректно вбить адрес например такой
Тамбовская Область, Город Мичуринск, Микрорайон Кочетовка, Улица Строительная, 10
Московская Область, Климовск Город, Южный Поселение, СНТ Весна-1 Улица
это как нибудь обходится?

**Comment by garakh** [comment]
Уточните пожалуйста, что означает «не возможно корректно вбить адрес»

**Comment by gvitaly** [comment]
Получается, что Город Мичуринск и Микрорайон Кочетовка нужно вбивать в одно и тоже поле.
Я впринципе обошел это использованием поиска в одной строке и разбором родителей, там  Город Мичуринск в этом случае будет как ownSity кажется(могу не точно написать). Но поиск адреса разбитый по полям, где присутствуют 3 и 4 уровни КЛАДР осуществить невозможно.
