### ISSUE TITLE
Не давать удалять DEL и BACKSPACE это специально?

### ISSUE THREAD

**Issue by garex** [garakh/kladrapi-jsclient#32]
https://github.com/garakh/kladrapi-jsclient/blob/6854f5616699703a67d940cac36bbbc85e02323e/kladr/js/kladr.js#L679

    if ((event.which > 8) && (event.which < 46)) {

М.б. имелось в виду?

    if ((event.which >= 8) && (event.which <= 46)) {

Если щас пулреквест закинуть, то ничего не будет? Или надо мейнтейнером стать?

**Comment by garakh** [comment]
Пуллреквест можно закинуть, глянем

**Comment by garex** [comment]
Илья, я просто пытаюсь понять — это специально так было сделано типа?

Щас мы читаем как:

    var backspaceCode = 8,
          deleteCode = 46; 
    if (event.which > backspaceCode && event.which < deleteCode) {

Т.е. ни "бэкспейс", ни "делете" не попадают в диапазон, на который идёт "отмена".

Или это просто обычная ошибка, когда хотели, чтоб они попадали, но забыли дописать "="?

Я это щас обнаружил на 1.4.1. Но и в current'е тоже есть. Как можно проверить, что это что-то другое не поломает, если включить удаляющие клавиши в условие отмены?

**Comment by garakh** [comment]
Не могу сходу так сказать. Наш коллега, который занимался этим плагином переехал и пока не может заниматься поддержкой. Поэтому нам надо самим посмотреть и понять баг это или фича.

**Comment by garakh** [comment]
Вообще, я не думаю, что он мог такое пропустить по ошибке, скорее всего это связанно с каким-то «мыслями».

**Comment by garex** [comment]
Я пока склоняюсь ближе к багу. Однако хотел бы на каком-нить хитром юс-кейсе проверить, что ничего другого не сломается. Где найти такой юс-кейс?

Если это "мысли", то почему так подозрительно близки к "запретным" удалятелям?

**Comment by garakh** [comment]
Есть примеры здесь https://github.com/garakh/kladrapi-jsclient/tree/master/examples 
попробовать с ними поиграться. 

>Если это "мысли", то почему так подозрительно близки к "запретным" удалятелям?

Рад бы ответить, но пока сам не знаю. Возможно и баг

**Comment by garex** [comment]
Ок, попробую на них поиграться и если там не сломается, то скину PR (с минифицированной версией).

**Comment by garex** [comment]
Нет нифига. Всё так и должно быть, как оно есть:

* если человек жмёт DEL или BACK, он уадаляет символы
* т.е. изменяет строку
* следовательно система должна запросить новую порцию
* => удалятели должны быть снаружи

То, что у нас локально бага скорее всего к версии 1.4.1 относится и нам надо обновиться.

See http://www.javascripter.net/faq/keycodes.htm

      8       8       8       8       8      Backspace
      9       9       9       9       9      Tab
     13      13      13      13      13      Enter
     16      16      16      16      16      Shift
     17      17      17      17      17      Ctrl
     18      18      18      18      18      Alt
     19      19      19      19      19      Pause, Break
     20      20      20      20      20      CapsLock
     27      27      27      27      27      Esc
     32      32      32      32      32      Space
     33      33      33      33      33      Page Up
     34      34      34      34      34      Page Down
     35      35      35      35      35      End
     36      36      36      36      36      Home
     37      37      37      37      37      Left arrow
     38      38      38      38      38      Up arrow
     39      39      39      39      39      Right arrow
     40      40      40      40      40      Down arrow
             44      44      44      44      PrntScrn (see below†)
     45      45      45      45      45      Insert
     46      46      46      46      46      Delete

**Comment by garakh** [comment]
ок
