### ISSUE TITLE
Как сделать, чтобы при вводе индекса подставлялись не только название, но и тип объекта?

### ISSUE THREAD

**Issue by berpcor** [garakh/kladrapi-jsclient#33]
Например, Краснодарский край. Подставляется Краснодарский. Какой смысл подставлять наименования без типа объекта? Плюс к этому - не меняется label у текстового поля.

**Comment by garakh** [comment]
Это просто примеры. Данные от сервера возвращаются, нужно подправить js код на клиентской стороне, чтоб он делал все, что вам необходимо.
