### ISSUE TITLE
Label в input street

### ISSUE THREAD

**Issue by CB9TOIIIA** [garakh/kladrapi-jsclient#41]
Всем привет! На demo видно, что улицы могут быть: бульвары, ГСК, проспекты и т.д.

Возник вопрос, как можно не менять label street - а записать в input label+street

Пример:

им Павла Корчагина  -> Бульвар им Павла Корчагина

**Comment by CB9TOIIIA** [comment]
`    valueFormat: function(obj, query) {
                    return obj.typeShort + ' ' + obj.name;
                }`

**Comment by garakh** [comment]
Я так понял вам удалось разобраться? Если да, то закрой пожалуйста issue
